<?php

namespace RebelCode\EddBookings\Block;

/**
 * Basic functionality of a block.
 *
 * @since [*next-version*]
 */
abstract class AbstractBlock implements BlockInterface
{
    /**
     * Gets the output generated by the block.
     *
     * @since [*next-version*]
     *
     * @return string The string output generated by this block.
     */
    abstract protected function _getOutput();

    /**
     * {@inheritdoc}
     *
     * @since [*next-version*]
     */
    public function __toString()
    {
        try {
            return (string) $this->_getOutput();
        } catch (\Exception $e) {
            return $e->getMessage();
        }
    }
}
